### ISSUE TITLE
More maintainers

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/attrs-feedstock#2]
@tacaswell @dstufft @hynek @Lukasa @Tinche
are any of you interested in being listed as maintainers?

**Comment by hynek** [comment]
heh it’s funny that you ask while I’m desperately trying to get more maintainers into attrs proper ;)  I’m sorry, as long as I’m not using conda at all, it doesn’t make any sense.

**Comment by Lukasa** [comment]
Honestly, I'm probably in the same boat as @hynek: I don't use conda at all and so I know very little about how its packaging model works.

**Comment by Tinche** [comment]
Sorry, I've never even used conda :(

**Comment by CJ-Wright** [comment]
@licode would you be interested? (this is a dep for the databroker stack)

**Comment by licode** [comment]
Please add me in. thanks.
